---

- name: Validate NCPA variables
  ansible.builtin.import_tasks: validate.yml
  tags: [ncpa, ncpa-install, ncpa-config]

- name: Install NCPA on Debian family
  ansible.builtin.import_tasks: Debian.yml
  when: ansible_facts['os_family'] == 'Debian'
  tags: [ncpa, ncpa-install]

- name: Install NCPA on RedHat family
  ansible.builtin.import_tasks: RedHat.yml
  when: ansible_facts['os_family'] == 'RedHat'
  tags: [ncpa, ncpa-install]

- name: Configure NCPA
  ansible.builtin.import_tasks: config.yml
  tags: [ncpa, ncpa-config]
